apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*ingress-nginx-controller*.log
        Tag               kube.ingress.* 
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off

    [INPUT]
        Name              tail
        Path              /var/log/containers/*log-generator*.log
        Tag               kube.backend.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off

    # === CPU/Memory 메트릭 수집 (30초 간격) ===
    [INPUT]
        Name              exec
        Command           sh -c 'kubectl top pods --no-headers --namespace=default | grep log-generator'
        Interval_Sec      30
        Tag               metrics.system
        Parser            kube_top

    # === Ingress 로그 파싱 ===

    # 1단계: Docker 컨테이너 로그 형식 파싱
    [FILTER]
        Name    parser
        Match   kube.ingress.*
        Key_Name log
        Parser  cri_log
        Reserve_Data On

    # 2단계: Nginx access log 파싱
    [FILTER]
        Name    parser
        Match   kube.ingress.*
        Key_Name message
        Parser  nginx_ingress
        Reserve_Data On

    # 3단계: 필드 추가
    [FILTER]
        Name    modify
        Match   kube.ingress.*
        Add     log_type http

    # === Backend 로그 파싱 ===

    # 1단계: Docker 컨테이너 로그 형식 파싱
    [FILTER]
        Name    parser
        Match   kube.backend.*
        Key_Name log
        Parser  cri_log
        Reserve_Data On

    # 2단계: JSON 내용 파싱
    [FILTER]
        Name    parser
        Match   kube.backend.*
        Key_Name message
        Parser  json_log
        Reserve_Data On

    # 3단계: 필드 추가
    [FILTER]
        Name    modify
        Match   kube.backend.*
        Add     log_type application

    # === 시스템 메트릭 변환 ===

    # 1단계: CPU 밀리코어(m)를 퍼센트로 변환 (1000m = 100%)
    # 2단계: 메모리 Mi를 퍼센트로 변환 (임시로 Mi 그대로 사용)
    [FILTER]
        Name    lua
        Match   metrics.system
        script  /fluent-bit/etc/metrics.lua
        call    transform_metrics

    # 3단계: 필드 추가 (service, namespace 등)
    [FILTER]
        Name    modify
        Match   metrics.system
        Add     service log-generator
        Add     namespace default
        Add     nodeName kind-control-plane

    # === 공통 정리 ===

    # 불필요한 필드 제거
    [FILTER]
        Name    record_modifier
        Match   *
        # Remove_key log
        # Remove_key message
        # Remove_key stream
        Remove_key logtag
        # Remove_key time
        Remove_key _p

    # === Kafka 출력 ===

    [OUTPUT]
        Name              kafka
        Match             kube.ingress.*
        Brokers           172.21.100.253:9092
        Topics            http
        Format            json

    [OUTPUT]
        Name              kafka
        Match             kube.backend.*
        Brokers           172.21.100.253:9092
        Topics            app
        Format            json

    [OUTPUT]
        Name              kafka
        Match             metrics.system
        Brokers           172.21.100.253:9092
        Topics            metrics.system
        Format            json

  parsers.conf: |
    # CRI/Kubernetes 컨테이너 로그 형식 파서
    # 형식: <timestamp> <stream> <logtag> <message>
    # 예: 2025-11-03T17:19:58.353137053Z stdout F actual log content here
    [PARSER]
        Name   cri_log
        Format regex
        Regex  ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On

    # Nginx Ingress Controller Access Log 파서
    [PARSER]
        Name   nginx_ingress
        Format regex
        Regex  ^(?<client_ip>[^ ]*) - (?<user>[^ ]*) \[(?<req_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<status_code>[^ ]*) (?<response_size>[^ ]*) "(?<referer>[^\"]*)" "(?<user_agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<upstream_service>[^\]]*)\] \[(?<upstream_alt_name>[^\]]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<request_id>.*)$
        Time_Key req_time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep On

    # Backend Application JSON 로그 파서
    [PARSER]
        Name   json_log
        Format json
        Time_Key @timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

    # Kubernetes 'kubectl top pods' 출력 파서
    # 형식: log-generator-abc123-xyz 150m 200Mi
    [PARSER]
        Name   kube_top
        Format regex
        Regex  ^(?<podName>[^\s]+)\s+(?<cpu_raw>[0-9]+)m\s+(?<memory_raw>[0-9]+)Mi

  metrics.lua: |
    function transform_metrics(tag, timestamp, record)
        -- CPU 밀리코어를 퍼센트로 변환 (1000m = 100%)
        if record["cpu_raw"] then
            local cpu_millis = tonumber(record["cpu_raw"])
            if cpu_millis then
                record["cpu"] = cpu_millis / 10.0  -- 1000m = 100%
            end
            record["cpu_raw"] = nil
        end

        -- 메모리 Mi를 그대로 사용 (나중에 퍼센트로 변환 가능)
        if record["memory_raw"] then
            local memory_mi = tonumber(record["memory_raw"])
            if memory_mi then
                record["memory"] = memory_mi  -- 임시로 Mi 값 그대로
            end
            record["memory_raw"] = nil
        end

        -- timestamp 추가 (Unix milliseconds)
        record["timestamp"] = timestamp * 1000

        return 2, timestamp, record
    end
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
